### PR TITLE
Add support for jsonnet

### PR DESCRIPTION
**Pull request by dbanetto**
# Intent

Add support for Jsonnet by using go-jsonnet's `jsonnetfmt`

### Type of change

- New feature or functionality (change which adds functionality)

**For changes visible to end-users**

- Breaking change (this change will force users to change their own code or config)
No.

- Relevant documentation has been updated
Yes

- Suggested release notes are provided below:

Added support for Jsonnet via go-jsonnet's `jsonnetfmt`

### Test plan

- Covered by existing test cases
- New test cases added

Yes, added `hello.jsonnet` & `hello.libsonnet` to the tests directory

- Manual testing; please provide instructions so we can reproduce:

I have tested this in my own (private) repo

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]
Awesome! thank you!

**Comment by alexeagle** [comment]
@dbanetto that failing test is asking you to update the README as well.

**Comment by dbanetto** [comment]
Hey @alexeagle, thanks for the pointer, looks to be all green now

**Review by alexeagle — APPROVED** [review]

**Comment by alexeagle** [comment]
Did you run the test locally? It still fails, I suspect it asserts the flags are alpha-sorted in the doc.

**Comment by alexeagle** [comment]
Did you run the test locally? It still fails, I suspect it asserts the flags are alpha-sorted in the doc.

**Comment by alexeagle** [comment]
Did you run the test locally? It still fails, I suspect it asserts the flags are alpha-sorted in the doc.

**Comment by alexeagle** [comment]
Did you run the test locally? It still fails, I suspect it asserts the flags are alpha-sorted in the doc.

**Pull request merged**
